### PR TITLE
Moved initPropertiesAndChildren before inserting into the DOM

### LINKED ISSUE #816: vdom.createDom creates intermediate DOM states
I am working with [A-Frame](https://aframe.io/) and Dojo 2 to render a scene in VR for a demo I've been working on called [Derpymon](https://github.com/devpaul/derpymon). I'm running into an issue with A-Frame's custom element throwing an exception due to missing required attributes (specifically A-Frame's [Asset Management System](https://aframe.io/docs/0.7.0/core/asset-management-system.html) has an element `a-asset-item` that expects a `src` attribute).

The problem is due to `vdom`'s `createDom()` function. When creating `v` elements it will [immediately attach them to the DOM before adding their attributes](https://github.com/dojo/widget-core/blob/master/src/vdom.ts#L780-L786). I was able to "fix" my issue by moving `initPropertiesAndChildren()` before attaching to the DOM. 

I'm not sure if this is a viable permanent solution or if there are reasons for attaching an element to the DOM before adding attributes; e.g. maybe some events are fired after attributes are added that may not be caught otherwise. React's provides a work-around for these cases by adding a special keyword `ref` that [allows access to the element](https://reactjs.org/docs/refs-and-the-dom.html). A-Frame's React wrapper [uses ref to ensure attributes are available](https://github.com/ngokevin/aframe-react/blob/master/src/index.js#L125), so another viable solution for Dojo may be to add a special Symbol that provides access to the element before adding it to the DOM.

As custom elements become more prevalent we'll definitely need a solution to this issue. Otherwise, we risk not being able to use custom elements with required attributes (or other similar expectations) with Dojo. FWIW, I've had a previous discussion with Maquette trying to come up with a solution in AFASSoftware/maquette#110.

Package Version: 0.2

**Code**
Here's a link to the problematic implementation of the custom-element:

https://github.com/devpaul/derpymon/blob/master/src/widgets/Assets.ts#L16-L18

**Expected behavior:**

Attributes should be attached to the element:

`<a-asset-item src="./path/to/model.obj">`

**Actual behavior:**

The element is initially rendered without attributes:

`<a-asset-item>`

### PR DESCRIPTION
**Pull request by devpaul**
Moved `initPropertiesAndChildren` in `vdom`'s `createDom` before the node is inserted into the DOM to prevent triggering observers and custom elements on an incomplete DOM. More details in the ticket.

Resolves #816

### CODE REVIEW

File: src/vdom.ts [hunk 1]
```diff
@@ -744,12 +744,13 @@ function createDom(
 			} else {
 				domNode = dnode.domNode;
 			}
+			// add attributes and children so we have a fully formed node prior to attach
```
Comment (agubler) [inline src/vdom.ts]: Not sure we need to add a comment for this

File: tests/unit/vdom.ts [hunk 2]
```diff
@@ -2708,4 +2711,39 @@ describe('vdom', () => {
 			});
 		});
 	});
+
+	describe('behavior', () => {
+		it('will append nodes with attributes already attached', function(this: Test) {
```
Comment (agubler) [inline tests/unit/vdom.ts]: I think this can use a param rather than `this` for skipping (and you shouldn't need to explicitly type `Test`), like:

```ts
it('will append nodes with attributes already attached',(test) => {
    if (!global.window || !global.window.hasOwnProperty('MutationObserver')) {
        test.skip('MutationObserver not present');
    }
    // ...
}
```

File: tests/unit/vdom.ts [hunk 3]
```diff
@@ -2708,4 +2711,39 @@ describe('vdom', () => {
...
+				childList: true,
+				subtree: true
+			});
+			const widget = new Foo();
+			dom.append(parent, widget.__render__() as VNode, widget);
+
+			const results = [...log, ...observer.takeRecords()];
+			observer.disconnect();
+			assert.isTrue(results.every((mutation) => mutation.type !== 'attributes'));
+			console.log(results);
```
Comment (agubler) [inline tests/unit/vdom.ts]: left a `console.log` in

File: tests/unit/vdom.ts [hunk 4]
```diff
@@ -2708,4 +2711,39 @@ describe('vdom', () => {
...
+			const parent = doc.createElement('div');
+			observer.observe(parent, {
+				attributes: true,
+				childList: true,
+				subtree: true
+			});
+			const widget = new Foo();
+			dom.append(parent, widget.__render__() as VNode, widget);
+
+			const results = [...log, ...observer.takeRecords()];
```
Comment (agubler) [inline tests/unit/vdom.ts]: Any reason you can't just do `log.push(...observer.takeRecords());` and use `log`?

File: tests/unit/vdom.ts [hunk 5]
```diff
@@ -1,6 +1,9 @@
+import Test from 'intern/lib/Test';
```
Comment (agubler) [inline tests/unit/vdom.ts]: As per the comment below, shouldn't need to import the `Test` type.

File: tests/unit/vdom.ts [hunk 6]
```diff
@@ -2708,4 +2711,39 @@ describe('vdom', () => {
...
+				}
+			}
+
+			const doc = global.window.document;
+			const log: MutationRecord[] = [];
+			const observer = new MutationObserver((mutations: MutationRecord[]) => {
+				log.push(...mutations);
+			});
+
+			const parent = doc.createElement('div');
```
Comment (agubler) [inline tests/unit/vdom.ts]: Everywhere else in the vdom tests we've just used `document` without needing the global shim

File: tests/unit/vdom.ts [hunk 7]
```diff
@@ -2708,4 +2711,38 @@ describe('vdom', () => {
...
+			observer.observe(parent, {
+				attributes: true,
+				childList: true,
+				subtree: true
+			});
+			const widget = new Foo();
+			dom.append(parent, widget.__render__() as VNode, widget);
```
Comment (agubler) [inline tests/unit/vdom.ts]: Don't need to `as VNode` here (I know there are other tests that still do)

File: tests/unit/vdom.ts (hunk 6 above)
Comment (agubler) [reply tests/unit/vdom.ts]: but if we are using it for the sniff then I guess no harm (although don't think we need to use `global` to do the `window` check either ¯\_(ツ)_/¯)

Comment (devpaul) [reply tests/unit/vdom.ts]: personally I have zero love and trust for JSDOM :). I'd be happy to use bare global calls if there's any benefit.

Comment (agubler) [reply tests/unit/vdom.ts]: Yeah there's no benefit so that's fine, we should probably be consistent through the all test in the future though.

File: src/vdom.ts (hunk 1 above)
Comment (devpaul) [reply src/vdom.ts]: It's probably worth a comment. Any place where order isn't apparent but required is worth mentioning.

Comment (agubler) [reply src/vdom.ts]: Hmmmm. Seemed pretty obvious being that it is actually directly before the code that does the attachment, but okay.

Comment (matt-gadd) [reply src/vdom.ts]: I don’t think this currently offers much value, if you feel the comment is needed can you expand upon it over “fully formed node” which doesn’t really mean anything.

File: tests/unit/vdom.ts [hunk 8]
```diff
@@ -2708,4 +2709,38 @@ describe('vdom', () => {
 			});
 		});
 	});
+
+	describe('behavior', () => {
```
Comment (matt-gadd) [inline tests/unit/vdom.ts]: This isn’t a great description, also is there any reason this year cannot be in the `create` or `properties` blocks elsewhere

File: tests/unit/vdom.ts [hunk 9]
```diff
@@ -2708,4 +2709,38 @@ describe('vdom', () => {
...
+		it('will append nodes with attributes already attached', (test) => {
+			if (!global.window || !global.window.hasOwnProperty('MutationObserver')) {
+				test.skip('MutationObserver not present');
+			}
+
+			class Foo extends WidgetBase {
```
Comment (matt-gadd) [inline tests/unit/vdom.ts]: Don’t think we need a widget to exercise this functionality do we? Any reason we can’t just use dom.create?

File: tests/unit/vdom.ts [hunk 10]
```diff
@@ -2708,4 +2709,38 @@ describe('vdom', () => {
 			});
 		});
 	});
+
+	describe('behavior', () => {
+		it('will append nodes with attributes already attached', (test) => {
+			if (!global.window || !global.window.hasOwnProperty('MutationObserver')) {
+				test.skip('MutationObserver not present');
+			}
```
Comment (matt-gadd) [inline tests/unit/vdom.ts]: It’s not great to skip a test due to the test using something that is potentially incompatible yet the actual code is. I’m not convinced a mutation observer is actually needed anyway, can you not just stub createElement and the associated things off it?

File: tests/unit/vdom.ts [hunk 11]
```diff
@@ -2708,4 +2709,38 @@ describe('vdom', () => {
 			});
 		});
 	});
+
+	describe('behavior', () => {
+		it('will append nodes with attributes already attached', (test) => {
```
Comment (matt-gadd) [inline tests/unit/vdom.ts]: This tests attributes, how about properties too?

File: src/vdom.ts (hunk 1 above)
Comment (matt-gadd) [reply src/vdom.ts]: To expand what I meant by not meaning anything, I mean as in describing why the ordering is important.

File: tests/unit/vdom.ts (hunk 8 above)
Comment (devpaul) [reply tests/unit/vdom.ts]: Yeah, I didn't know where to put it. Refactoring the test to use `dom.create()` will make it easier to house in that test suite.

File: tests/unit/vdom.ts (hunk 11 above)
Comment (devpaul) [reply tests/unit/vdom.ts]: The intention of the test is that `setProperties` was called before `attachNode`. I wanted to avoid describing internal functions in the test. Would it be more clear with another name?

File: src/vdom.ts (hunk 1 above)
Comment (devpaul) [reply src/vdom.ts]: There's a test that covers this now. If a future developer changes this they'll fail the test and can back-track through issues.

File: tests/unit/vdom.ts [hunk 12]
```diff
@@ -71,6 +73,10 @@ describe('vdom', () => {
 	afterEach(() => {
 		consoleStub.restore();
 		resolvers.restore();
+		for (let spy of spys) {
```
Comment (matt-gadd) [inline tests/unit/vdom.ts]: could use sinon.sandbox instead for this (then we wouldn't need the for and it's useful for other things), but not blocking this PR going in.

File: tests/unit/vdom.ts [hunk 13]
```diff
@@ -1421,6 +1427,28 @@ describe('vdom', () => {
...
+					appendedHtml.push(node.outerHTML);
+					return appendChild(node);
+				});
+				return node;
+			});
+			spys.push(createElementStub);
+			const projection = dom.create(v('div', { 'data-attr': 'test' }), projectorStub);
+
+			assert.strictEqual(projection.domNode.innerHTML, expected);
+			assert.lengthOf(appendedHtml, 1);
```
Comment (matt-gadd) [inline tests/unit/vdom.ts]: given this PR is about an ordering change, it would've been nice to have a slightly more expressive assertion for that. ie sinon keeps track of call orders across spies/stubs so we could've done something like:
```ts
assert.isTrue(appendChildSpy.calledAfter(setAttributeSpy));
```
anyway this isn't blocking us taking this 👍.

File: tests/unit/vdom.ts (hunk 12 above)
Comment (devpaul) [reply tests/unit/vdom.ts]: That would be a good refactor for this test suite 👍
