### PR TITLE
Fix benchmarks

### LINKED ISSUE #928: Benchmarks are not running correclty
**Bug**

Currently running `npm run benchmark` after a correct `npm install` fails, preventing you from benchmarking dojo widgets.

Package Version: v2.0.2-pre

**Code**

`npm run benchmark`

**Expected behavior:**

Run the provided benchmarks to completion

**Actual behavior:**

Currently the command errors out with the following output:

```shell

Benchmark failed { WebDriverError: unknown error: call function result missing 'value'
  (Session info: headless chrome=67.0.3396.62)
  (Driver info: chromedriver=2.33.506092 (733a02544d189eeb751fe0d7ddca79a0ee28cce4),platform=Linux 4.13.0-39-generic x86_64)
    at Object.checkLegacyResponse (/home/james/Code/SitePen/dojo/widget-core/node_modules/selenium-webdriver/lib/error.js:546:15)
    at parseHttpResponse (/home/james/Code/SitePen/dojo/widget-core/node_modules/selenium-webdriver/lib/http.js:509:13)
    at doSend.then.response (/home/james/Code/SitePen/dojo/widget-core/node_modules/selenium-webdriver/lib/http.js:441:30)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) name: 'WebDriverError', remoteStacktrace: '' }

```

### PR DESCRIPTION
**Pull request by JamesMilnerUK**
**Type:**  Bug

The following has been addressed in the PR:

* [x] There is a related issue
* [x] All code has been formatted with [`prettier`](https://prettier.io/) as per the [readme code style guidelines](./../#code-style)
* [x] Unit or Functional tests are included in the PR

**Description:**

Currently benchmarks do not work as expected. Running `npm run benchmark` doesn't complete. This PR fixes that so that benchmarks run correctly. It also:

* Adds build as a npm script
* Allows headless and regular running of benchmarks as npm scripts
* Replaces the benchmark shell script with a JavaScript file for cross-compatibility

Resolves #928

### CODE REVIEW

File: tests/benchmark/runner/src/benchmarkCli.ts [hunk 1]
```diff
@@ -0,0 +1,39 @@
...
+	)
+	.help('help')
+	.default('check', 'false')
+	.default('exitOnError', 'false')
+	.default('count', config.REPEAT_RUN)
+	.boolean('headless')
+	.array('framework')
+	.array('benchmark').argv;
+
+console.log(args);
```
Comment (agubler) [inline tests/benchmark/runner/src/benchmarkCli.ts]: do we need this console.log here?

Comment (JamesMilnerUK) [reply tests/benchmark/runner/src/benchmarkCli.ts]: Nope! Sorry I just caught that but hadn't pushed it
