### PR TITLE
Deffering custom element children until after the node is created

### LINKED ISSUE #517: Creating Custom Element throws error
It's currently not possible to create a custom element programmatically using `document.createElement`, you get the following error:
```
DOMException: Failed to execute 'createElement' on 'Document': 
The result must not have children
```
The spec says the following on elements:
```
The element must not gain any attributes or children, 
as this violates the expectations of consumers who use the createElement 
or createElementNS methods.
```

### PR DESCRIPTION
**Pull request by rorticus**
**Type:** bug

The following has been addressed in the PR:

* [x] There is a related issue
* [x] All code matches the [style guide](https://github.com/dojo/meta/blob/master/STYLE.md)
* [x] Unit or Functional tests are included in the PR

**Description:**

Creating a custom element manually (`document.createElement`) causes an error because elements are not supposed to be created with children (the projector). We're now deferring the appending of the projector until after the element is attached to the dom.

Resolves #517

### CODE REVIEW

File: src/registerCustomElement.ts [hunk 1]
```diff
@@ -25,10 +25,20 @@ export function registerCustomElement(descriptorFactory: CustomElementDescriptor
...
+
 		constructor() {
 			super();
 
-			initializeElement(this);
+			this._appender = initializeElement(this);
+		}
+
+		connectedCallback() {
+			if (!this._isAppended && this._appender) {
```
Comment (agubler) [inline src/registerCustomElement.ts]: you are missing a test branch here though.

Comment (rorticus) [inline src/registerCustomElement.ts]: Yup, just saw that. Working on that now!
