### PR TITLE
Decouple initial set properties from the widget base constructor

### LINKED ISSUE #356: Initial 'properties:changed' event fires too late
**Enhancement** 

In order to provide support for decorator functionality in non decorator environments and prevent the need to manually call "set up" functions from constructors to deal with the initial properties, we need to address the point in the lifecycle where properties initially get set.

Currently this is in the constructor of widget base which means that the event has already fired before the sub classes' functions have been registered.

Proposal is to stop setting the properties during construction and call `setProperties` as a second action, in most cases this will still be internal to widget base in `dNodeToVNode` with the exception of when dealing with a projector widget.

### PR DESCRIPTION
**Pull request by agubler**
**Type:** feature

The following has been addressed in the PR:

* [x] There is a related issue
* [x] All code matches the [style guide](https://github.com/dojo/meta/blob/master/STYLE.md)
* [x] Unit or Functional tests are included in the PR

**Description:**

As described by the issue, with the initial setProperties occurring in WidgetBase constructor it means that the first event is missed by sub classes and inadvertently promotes a pattern of putting logic in the constructor. This can be a problem for non decorator alternatives to decorators provided functionality, such as `@theme` as there is no reasonable way to ensure that `this.baseClasses` is available in in the mixins constructor.

This will become a core principle of Dojo 2 widgets, that only variable initialisation and listening to events (`.on`) should happen in the constructor.

Resolves #356

### CODE REVIEW

File: src/mixins/Themeable.ts [hunk 1]
```diff
@@ -273,7 +278,18 @@ export function ThemeableMixin<T extends Constructor<WidgetBase<WidgetProperties
...
 
 			if (themeChanged || overrideClassesChanged) {
-				this.generatedClassNames = this.generateThemeClasses(this.baseClasses, theme, overrideClasses);
+				this.initialised ?
+					this.generateThemeClasses(this.baseClasses, theme, overrideClasses) :
+					this.initiliaseClasses();
+			}
+		}
+
+		private initiliaseClasses() {
```
Comment (agubler) [inline src/mixins/Themeable.ts]: Some doc and update to US spelling.

File: src/mixins/Themeable.ts [hunk 2]
```diff
@@ -159,15 +159,19 @@ export function ThemeableMixin<T extends Constructor<WidgetBase<WidgetProperties
 		private generatedClassNames: ClassNameFlagsMap;
 
 		/**
+		 * Indicates if the base classes have been initialised.
+		 */
+		private initialised: boolean;
```
Comment (agubler) [inline src/mixins/Themeable.ts]: US spelling please.

File: src/WidgetBase.ts [hunk 3]
```diff
@@ -134,23 +133,21 @@ export class WidgetBase<P extends WidgetProperties> extends Evented implements W
...
+	public setProperties(properties: P): void {
 		const diffPropertyResults: { [index: string]: PropertyChangeRecord } = {};
 		const diffPropertyChangedKeys: string[] = [];
 
 		this.bindFunctionProperties(properties);
 
 		this.diffPropertyFunctionMap.forEach((property: string, diffFunctionName: string) => {
 			const previousProperty = this.previousProperties[property];
-			const newProperty = properties[property];
+			const newProperty = (<any> properties)[property];
```
Comment (agubler) [inline src/WidgetBase.ts]: Does anyone know a better way to do this? I don't want an index type on the object (WidgetProperties) as would like it to correctly report unknown properties...?

File: src/mixins/Themeable.ts (hunk 1 above)
Comment (dylans) [inline src/mixins/Themeable.ts]: that's neither US nor UK spelling there ;)

Comment (agubler) [inline src/mixins/Themeable.ts]: haha indeed.

File: src/mixins/Themeable.ts [hunk 4]
```diff
@@ -273,7 +278,21 @@ export function ThemeableMixin<T extends Constructor<WidgetBase<WidgetProperties
...
 			if (themeChanged || overrideClassesChanged) {
-				this.generatedClassNames = this.generateThemeClasses(this.baseClasses, theme, overrideClasses);
+				this.initialized ?
+					this.generateThemeClasses(this.baseClasses, theme, overrideClasses) :
+					this.initializeClasses();
+			}
+		}
+
+		/**
+		 * Initialize the reverse loop up map and the generatedThemeClasses.
```
Comment (matt-gadd) [inline src/mixins/Themeable.ts]: reverse loop?

Comment (agubler) [inline src/mixins/Themeable.ts]: I don't know what you are referring to 😉
