### PR TITLE
Fix incorrect typings for WebAnimations

### LINKED ISSUE #814: WebAnimations meta typing should allow animation properties to be passed as function
**Bug** 

Code allows `WebAnimations` to be passed `AnimationProperties`, or `() => AnimationProperties`, or an array of either. However, it's typings currently do not allow a function.

### PR DESCRIPTION
**Pull request by tomdye**
**Type:** bug

The following has been addressed in the PR:

* [x] There is a related issue
* [x] All code has been formatted with [`prettier`](https://prettier.io/) as per the [readme code style guidelines](./../#code-style)
* [x] Unit or Functional tests are included in the PR

**Description:**

- Changes AnimationProperties to allow array of functions or properties.
- Types the `effects` array (currently any)

Resolves #814

### CODE REVIEW

File: src/meta/WebAnimation.ts [hunk 1]
```diff
@@ -113,7 +117,12 @@ export class WebAnimations extends Base {
 		}
 	}
 
-	animate(key: string, animateProperties: AnimationProperties | AnimationProperties[]) {
+	animate(
+		key: string,
+		animateProperties:
+			| AnimationPropertiesOrAnimationPropertiesFunction
```
Comment (umaar) [inline src/meta/WebAnimation.ts]: The leading pipe surprised me but them Tom pointed out it was this! https://github.com/prettier/prettier/issues/2069

**Comment by tomdye** [comment]
@agubler are you happy with the naming now?
