### PR TITLE
Fix Edge failures

### LINKED ISSUE #679: widget core tests failing in edge sporadically
**Bug** 

Tests seem to be failing in widget-core on edge platform sporadically.
This is due to the `afterCreate` function changing due to recent nodeHandler changes. This error is hidden by a timing based issue.

### PR DESCRIPTION
**Pull request by tomdye**
**Type:** bug

The following has been addressed in the PR:

* [x] There is a related issue
* [x] All code matches the [style guide](https://github.com/dojo/meta/blob/master/STYLE.md)
* [x] Unit or Functional tests are included in the PR

**Description:**

Fixes edge failures. Makes certain tests sync

Resolves #679

### CODE REVIEW

File: src/WidgetBase.ts [hunk 1]
```diff
@@ -193,6 +193,8 @@ export class WidgetBase<P = WidgetProperties, C extends DNode = DNode> extends E
 
 	private _numRootNodes = 0;
 
+	private _rootNodeKeys: object[];
```
Comment (matt-gadd) [inline src/WidgetBase.ts]: is a root node key really an object?

Comment (tomdye) [reply src/WidgetBase.ts]: Got a typing error when i set it to `string[]`. The typedoc popup said that `properties.key` is an object.
screenshot 2017-09-15 09 44 15
